name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  trigger-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger deployment workflow
        uses: actions/github-script@v6
        with:
          script: |
            const { github, context } = require('@actions/github');
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yaml',
              ref: context.ref,
            });
