name: Deploy

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to platform
        run: echo "Deploying to platform with image moshedana/sela-demo:${{ inputs.image_tag }}"
        # Add actual deployment commands here
