name: Deploy

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          
