name: Deploy Pipeline

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploying to platform
        run: |
          echo "Deploying image ${{ inputs.image }} to platform..."

